name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔥
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run docs:build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          access_token: ${{ secrets.VUE_ADMIN_TEMPLATE }}
          branch: main # The branch the action should deploy to.
          folder: docs/.vuepress/dist
          repository_name: Boom-Gh/boom-gh.github.io
          target_folder: vuepress-demo